### ISSUE TITLE
osx crash on start

### ISSUE THREAD

**Issue by wickedwzrd** [Pewpews/happypanda#29]
I have all of the dependencies installed and I ran main.py and got this error message:
Traceback (most recent call last):
  File "/Users/thomas/HappyPanda/happypanda-master/version/main.py", line 226, in <module>
    start()
  File "/Users/thomas/HappyPanda/happypanda-master/version/main.py", line 221, in start
    start_main_window(conn)
  File "/Users/thomas/HappyPanda/happypanda-master/version/main.py", line 153, in start_main_window
    WINDOW = app.AppWindow()
  File "/Users/thomas/HappyPanda/happypanda-master/version/app.py", line 53, in **init**
    self.initUI()
  File "/Users/thomas/HappyPanda/happypanda-master/version/app.py", line 287, in initUI
    self.notification_bar = misc.NotificationOverlay(self)
  File "/Users/thomas/HappyPanda/happypanda-master/version/misc.py", line 439, in **init**
    self.slide_animation = QPropertyAnimation(self, 'minimumHeight')
TypeError: arguments did not match any overloaded call:
  QPropertyAnimation(QObject parent=None): too many arguments
  QPropertyAnimation(QObject, QByteArray, QObject parent=None): argument 2 has unexpected type 'str'

If I knew python I would probably be able to fix this but since I don't would you be able to help me?

**Comment by twiddli** [comment]
This seems to be a mac-only issue. The fix should be simple:
On line `19` after `QPropertyAnimation` but before the parentheses, set a comma and then write `QByteArray`. 
So it should look like this: `QPropertyAnimaton, QByteArray)`.

After that go to line `439` and at the end replace `'minimumHeight'` with `QByteArray('minimumHeight')`

I haven't tested this. I'm at the phone so I can't provide the code, but this should fix the issue. You'll have to wait till I get home if it doesn't work.

**Comment by wickedwzrd** [comment]
Still doesn't work. I got this error now:
File "/Users/thomas/HappyPanda/happypanda-master/version/misc.py", line 439, in **init**
    self.slide_animation = QPropertyAnimation(self, QByteArray('minimumHeight'))
TypeError: arguments did not match any overloaded call:
  QByteArray(): too many arguments
  QByteArray(int, str): argument 1 has unexpected type 'str'
  QByteArray(QByteArray): argument 1 has unexpected type 'str'

**Comment by twiddli** [comment]
Alright, I'm home.
I pushed some changes to the master branch. If you cloned the repo, then do a `git pull`.
If not, go and redownload the `misc.py` file [here](https://github.com/Pewpews/happypanda/blob/master/version/misc.py).
Like I previously mentioned, this seems to be a mac-only issue. I couldn't really test for any faults or anything, but I think everything should be fixed now;

**Comment by wickedwzrd** [comment]
Yup looks like everything seems to be fixed. Thanks for the help.
